[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]

# ssr
[build]
#target = "x86_64-unknown-linux-gnu" # or whatever
rustflags = ["--cfg=has_std"]
